/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'fcruner'
*/

#include <windows.h>
#include <fdi.h>
#include "defs.h"

#define __thiscall __fastcall
#define this _this

struct FancyUpdateDialog;
struct IMoniker;
struct IStream;
struct IBindCtx;
struct FancyDownloaderCallback;
struct IBindStatusCallbackVtbl;
struct IBinding;
struct IHttpNegotiateVtbl;
struct FancyBaseDialogVtbl;

/* 67 */
struct FancyStr
{
  char *buffer;
  int len;
  int capacity;
};

/* 68 */
struct CacheStore
{
  FancyStr strPath;
  FancyStr strBufferUnused;
  FancyStr strDrive;
  FancyStr strFullPath;
  FancyStr strSystem;
};

/* 66 */
struct FancyBox
{
  HMODULE hObjsys;
  int (__cdecl *fStdInitFancyBox)(HMODULE hModule, HWND hWnd, int, int);
  void (__cdecl *fStdCmdFancyBox)(int a1, char *a2);
  HINSTANCE hInstance;
  HWND hWnd;
  FancyStr strCommandDll;
  FancyStr strCommandRaw;
  FancyStr field_2C;
  FancyStr field_38;
  FancyStr objsysDllPath;
  FancyStr field_50;
  FancyStr strCommandSystem;
  int field_68;
  int objsysReady;
  int field_70;
  int field_74;
  FancyStr cmdLine;
  FancyStr strCommandSV;
  FancyStr strCommandC;
  FancyStr strCommandI;
  char field_A8;
  int field_AC[382];
  int field_6A4;
  int field_6A8;
  int field_6AC[383];
  int field_CA8;
  int field_CAC[3];
  int field_CB8[3];
  FancyStr updateMessage;
  int field_CD0;
  int field_CD4;
  int field_CD8;
  int field_CDC;
  int field_CE0;
  FancyUpdateDialog *updateDialog;
  CacheStore field_CE8;
};

/* 69 */
struct __declspec(align(4)) FancyBaseDialog
{
  FancyBaseDialogVtbl *__vftbl;
  int field_4;
  int field_8;
  HWND hDialog;
  HWND hWndParent;
  int field_14;
};

/* 70 */
struct __declspec(align(4)) FancyUpdateDialog : FancyBaseDialog
{
  HWND downloadingTextControl;
  HWND downloadProgressControl;
  HWND updateProgressControl;
  int field_24;
  int field_28;
  int width;
  int height;
};

/* 77 */
struct FancyBoxFileContent
{
  int buffer;
  int capacity;
  int fileSize;
  int readSize;
  int paddingSize;
};

/* 78 */
struct FancyCab
{
  int __vftbl;
  __int16 files;
  __int16 folders;
  int cabSize;
  char field_C[256];
  char field_10C[256];
  char field_20C[256];
  int field_30C;
  int field_310;
  HFDI hFDI;
  char **filenames;
  int filenameSize;
};

/* 46 */
typedef void *HANDLE;

/* 79 */
struct FancyBoxFile
{
  int bOpened;
  FancyStr Filename;
  HANDLE hFile;
};

/* 80 */
struct FancyDownloader
{
  FancyDownloaderCallback *callback;
  IMoniker *urlMoniker;
  IBindCtx *bindCtx;
  IStream *iStream;
  FancyStr netPath;
  FancyStr localPath;
  FancyStr filename;
  int buffer;
  int capacity;
  int size;
  int contentLength;
  int lastModified;
  int field_48;
  int field_4C;
  int stage;
  int completed;
  int field_58;
  void (__cdecl *fUpdateProgress)(int, unsigned int);
};

///* 198 */
//#pragma pack(push, 8)
//struct IBindStatusCallback
//{
//  struct IBindStatusCallbackVtbl *lpVtbl;
//};
//#pragma pack(pop)
//
///* 228 */
//#pragma pack(push, 8)
//struct IHttpNegotiate
//{
//  struct IHttpNegotiateVtbl *lpVtbl;
//};
//#pragma pack(pop)

/* 230 */
struct FancyDownloaderSubCallback : IHttpNegotiate
{
  int refCount;
  IBinding *binding;
  IStream *stream;
  FancyDownloader *downloader;
  int completed;
  FancyStr url;
};

/* 197 */
struct FancyDownloaderCallback : IBindStatusCallback, FancyDownloaderSubCallback
{
};

/* 236 */
struct FancyLinedText
{
  int __vftbl;
  int size;
  int count;
  char **line;
};

/* 238 */
struct FancyBaseDialogVtbl
{
  void (__thiscall *InitialzeComponent)(FancyBaseDialog* this);
  int (__thiscall *Release)(FancyBaseDialog *this);
  void *nullsub;
  FancyBaseDialog *(__thiscall *field_C)(FancyBaseDialog* this, char);
  int (__thiscall *OnMessage)(FancyBaseDialog* this, int, int, int, int);
};

